package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * AttachmentDetails generated by hbm2java
 */
public class AttachmentDetails  implements java.io.Serializable {


     private Long attachmentId;
     private Long contactDetailsId;
     private String attachmentName;
     private String attachmentLocation;
     private Long fileSize;
     private String fileType;
     private Long uploadedTime;

    public AttachmentDetails() {
    }

    public AttachmentDetails(Long contactDetailsId, String attachmentName, String attachmentLocation, Long fileSize, String fileType, Long uploadedTime) {
       this.contactDetailsId = contactDetailsId;
       this.attachmentName = attachmentName;
       this.attachmentLocation = attachmentLocation;
       this.fileSize = fileSize;
       this.fileType = fileType;
       this.uploadedTime = uploadedTime;
    }
   
    public Long getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }
    public Long getContactDetailsId() {
        return this.contactDetailsId;
    }
    
    public void setContactDetailsId(Long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public String getAttachmentName() {
        return this.attachmentName;
    }
    
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName;
    }
    public String getAttachmentLocation() {
        return this.attachmentLocation;
    }
    
    public void setAttachmentLocation(String attachmentLocation) {
        this.attachmentLocation = attachmentLocation;
    }
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }
    public String getFileType() {
        return this.fileType;
    }
    
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }
    public Long getUploadedTime() {
        return this.uploadedTime;
    }
    
    public void setUploadedTime(Long uploadedTime) {
        this.uploadedTime = uploadedTime;
    }




}


