package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * ClientContactDetails generated by hbm2java
 */
public class ClientContactDetails  implements java.io.Serializable {


     private Long contactDetailsId;
     private String name;
     private String email;
     private String phoneNumber;
     private String countryCode;
     private String projectBreif;
     private String addedLinks;
     private Boolean isAttachments;
     private Long attachmentId;

    public ClientContactDetails() {
    }

    public ClientContactDetails(String name, String email, String phoneNumber, String countryCode, String projectBreif, String addedLinks, Boolean isAttachments, Long attachmentId) {
       this.name = name;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.countryCode = countryCode;
       this.projectBreif = projectBreif;
       this.addedLinks = addedLinks;
       this.isAttachments = isAttachments;
       this.attachmentId = attachmentId;
    }
   
    public Long getContactDetailsId() {
        return this.contactDetailsId;
    }
    
    public void setContactDetailsId(Long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getProjectBreif() {
        return this.projectBreif;
    }
    
    public void setProjectBreif(String projectBreif) {
        this.projectBreif = projectBreif;
    }
    public String getAddedLinks() {
        return this.addedLinks;
    }
    
    public void setAddedLinks(String addedLinks) {
        this.addedLinks = addedLinks;
    }
    public Boolean getIsAttachments() {
        return this.isAttachments;
    }
    
    public void setIsAttachments(Boolean isAttachments) {
        this.isAttachments = isAttachments;
    }
    public Long getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }




}


