package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Contactus generated by hbm2java
 */
public class Contactus  implements java.io.Serializable {


     private Long contactId;
     private long time;
     private String name;
     private String email;
     private String message;
     private long generatedTokenId;

    public Contactus() {
    }

	
    public Contactus(long time, String email, long generatedTokenId) {
        this.time = time;
        this.email = email;
        this.generatedTokenId = generatedTokenId;
    }
    public Contactus(long time, String name, String email, String message, long generatedTokenId) {
       this.time = time;
       this.name = name;
       this.email = email;
       this.message = message;
       this.generatedTokenId = generatedTokenId;
    }
   
    public Long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }
    public long getTime() {
        return this.time;
    }
    
    public void setTime(long time) {
        this.time = time;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public long getGeneratedTokenId() {
        return this.generatedTokenId;
    }
    
    public void setGeneratedTokenId(long generatedTokenId) {
        this.generatedTokenId = generatedTokenId;
    }




}


