package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * Notifyme generated by hbm2java
 */
public class Notifyme  implements java.io.Serializable {


     private Long notifymeId;
     private long time;
     private String email;
     private String browserDetails;
     private String country;

    public Notifyme() {
    }

	
    public Notifyme(long time, String email) {
        this.time = time;
        this.email = email;
    }
    public Notifyme(long time, String email, String browserDetails, String country) {
       this.time = time;
       this.email = email;
       this.browserDetails = browserDetails;
       this.country = country;
    }
   
    public Long getNotifymeId() {
        return this.notifymeId;
    }
    
    public void setNotifymeId(Long notifymeId) {
        this.notifymeId = notifymeId;
    }
    public long getTime() {
        return this.time;
    }
    
    public void setTime(long time) {
        this.time = time;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getBrowserDetails() {
        return this.browserDetails;
    }
    
    public void setBrowserDetails(String browserDetails) {
        this.browserDetails = browserDetails;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


