package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * PsdToEmailPaidOption generated by hbm2java
 */
public class PsdToEmailPaidOption  implements java.io.Serializable {


     private Long emailPaidAddonId;
     private Long emailIntegrationId;
     private Boolean isResponsive;
     private String mobileCompatability;

    public PsdToEmailPaidOption() {
    }

    public PsdToEmailPaidOption(Long emailIntegrationId, Boolean isResponsive, String mobileCompatability) {
       this.emailIntegrationId = emailIntegrationId;
       this.isResponsive = isResponsive;
       this.mobileCompatability = mobileCompatability;
    }
   
    public Long getEmailPaidAddonId() {
        return this.emailPaidAddonId;
    }
    
    public void setEmailPaidAddonId(Long emailPaidAddonId) {
        this.emailPaidAddonId = emailPaidAddonId;
    }
    public Long getEmailIntegrationId() {
        return this.emailIntegrationId;
    }
    
    public void setEmailIntegrationId(Long emailIntegrationId) {
        this.emailIntegrationId = emailIntegrationId;
    }
    public Boolean getIsResponsive() {
        return this.isResponsive;
    }
    
    public void setIsResponsive(Boolean isResponsive) {
        this.isResponsive = isResponsive;
    }
    public String getMobileCompatability() {
        return this.mobileCompatability;
    }
    
    public void setMobileCompatability(String mobileCompatability) {
        this.mobileCompatability = mobileCompatability;
    }




}


