package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * PsdToHtmlOrdernow generated by hbm2java
 */
public class PsdToHtmlOrdernow  implements java.io.Serializable {


     private Long orderId;
     private long contactDetailsId;
     private long freeAddonId;
     private Long paidAddonId;
     private Integer numberOfLandingPage;
     private Integer numberOfInnerPage;

    public PsdToHtmlOrdernow() {
    }

	
    public PsdToHtmlOrdernow(long contactDetailsId, long freeAddonId) {
        this.contactDetailsId = contactDetailsId;
        this.freeAddonId = freeAddonId;
    }
    public PsdToHtmlOrdernow(long contactDetailsId, long freeAddonId, Long paidAddonId, Integer numberOfLandingPage, Integer numberOfInnerPage) {
       this.contactDetailsId = contactDetailsId;
       this.freeAddonId = freeAddonId;
       this.paidAddonId = paidAddonId;
       this.numberOfLandingPage = numberOfLandingPage;
       this.numberOfInnerPage = numberOfInnerPage;
    }
   
    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }
    public long getContactDetailsId() {
        return this.contactDetailsId;
    }
    
    public void setContactDetailsId(long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public long getFreeAddonId() {
        return this.freeAddonId;
    }
    
    public void setFreeAddonId(long freeAddonId) {
        this.freeAddonId = freeAddonId;
    }
    public Long getPaidAddonId() {
        return this.paidAddonId;
    }
    
    public void setPaidAddonId(Long paidAddonId) {
        this.paidAddonId = paidAddonId;
    }
    public Integer getNumberOfLandingPage() {
        return this.numberOfLandingPage;
    }
    
    public void setNumberOfLandingPage(Integer numberOfLandingPage) {
        this.numberOfLandingPage = numberOfLandingPage;
    }
    public Integer getNumberOfInnerPage() {
        return this.numberOfInnerPage;
    }
    
    public void setNumberOfInnerPage(Integer numberOfInnerPage) {
        this.numberOfInnerPage = numberOfInnerPage;
    }




}


