package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * PsdToEmailOrdernow generated by hbm2java
 */
public class PsdToEmailOrdernow  implements java.io.Serializable {


     private Long psdtoemailOrderId;
     private Long contactDetailsId;
     private long numberOfPage;
     private Long mailPaidOptionId;
     private Long mailFreeOptionId;

    public PsdToEmailOrdernow() {
    }

	
    public PsdToEmailOrdernow(long numberOfPage) {
        this.numberOfPage = numberOfPage;
    }
    public PsdToEmailOrdernow(Long contactDetailsId, long numberOfPage, Long mailPaidOptionId, Long mailFreeOptionId) {
       this.contactDetailsId = contactDetailsId;
       this.numberOfPage = numberOfPage;
       this.mailPaidOptionId = mailPaidOptionId;
       this.mailFreeOptionId = mailFreeOptionId;
    }
   
    public Long getPsdtoemailOrderId() {
        return this.psdtoemailOrderId;
    }
    
    public void setPsdtoemailOrderId(Long psdtoemailOrderId) {
        this.psdtoemailOrderId = psdtoemailOrderId;
    }
    public Long getContactDetailsId() {
        return this.contactDetailsId;
    }
    
    public void setContactDetailsId(Long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public long getNumberOfPage() {
        return this.numberOfPage;
    }
    
    public void setNumberOfPage(long numberOfPage) {
        this.numberOfPage = numberOfPage;
    }
    public Long getMailPaidOptionId() {
        return this.mailPaidOptionId;
    }
    
    public void setMailPaidOptionId(Long mailPaidOptionId) {
        this.mailPaidOptionId = mailPaidOptionId;
    }
    public Long getMailFreeOptionId() {
        return this.mailFreeOptionId;
    }
    
    public void setMailFreeOptionId(Long mailFreeOptionId) {
        this.mailFreeOptionId = mailFreeOptionId;
    }




}


