package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * PsdToEmailFreeOption generated by hbm2java
 */
public class PsdToEmailFreeOption  implements java.io.Serializable {


     private Long emailFreeAddonId;
     private String supportedPlatforms;

    public PsdToEmailFreeOption() {
    }

    public PsdToEmailFreeOption(String supportedPlatforms) {
       this.supportedPlatforms = supportedPlatforms;
    }
   
    public Long getEmailFreeAddonId() {
        return this.emailFreeAddonId;
    }
    
    public void setEmailFreeAddonId(Long emailFreeAddonId) {
        this.emailFreeAddonId = emailFreeAddonId;
    }
    public String getSupportedPlatforms() {
        return this.supportedPlatforms;
    }
    
    public void setSupportedPlatforms(String supportedPlatforms) {
        this.supportedPlatforms = supportedPlatforms;
    }




}


