package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * PsdToHtmlFreeOptions generated by hbm2java
 */
public class PsdToHtmlFreeOptions  implements java.io.Serializable {


     private Long freeAddonId;
     private String layout;
     private String font;
     private String nonWebFont;
     private Boolean advancedSemanticData;
     private Boolean wcag2;
     private Boolean dynamicDropDownMenu;
     private Boolean dreamweaverCompatability;
     private String browserCompatability;
     private Boolean wcag2_1;
     private String cssVersion;
     private Boolean commentedCss;
     private String codingType;
     private Boolean commentedHtml;
     private Boolean optimizedForLoadSpeed;
     private Boolean seoSemanticCoding;
     private String jsLibrary;
     private Boolean corouselImage;
     private Boolean tooltip;

    public PsdToHtmlFreeOptions() {
    }

    public PsdToHtmlFreeOptions(String layout, String font, String nonWebFont, Boolean advancedSemanticData, Boolean wcag2, Boolean dynamicDropDownMenu, Boolean dreamweaverCompatability, String browserCompatability, Boolean wcag2_1, String cssVersion, Boolean commentedCss, String codingType, Boolean commentedHtml, Boolean optimizedForLoadSpeed, Boolean seoSemanticCoding, String jsLibrary, Boolean corouselImage, Boolean tooltip) {
       this.layout = layout;
       this.font = font;
       this.nonWebFont = nonWebFont;
       this.advancedSemanticData = advancedSemanticData;
       this.wcag2 = wcag2;
       this.dynamicDropDownMenu = dynamicDropDownMenu;
       this.dreamweaverCompatability = dreamweaverCompatability;
       this.browserCompatability = browserCompatability;
       this.wcag2_1 = wcag2_1;
       this.cssVersion = cssVersion;
       this.commentedCss = commentedCss;
       this.codingType = codingType;
       this.commentedHtml = commentedHtml;
       this.optimizedForLoadSpeed = optimizedForLoadSpeed;
       this.seoSemanticCoding = seoSemanticCoding;
       this.jsLibrary = jsLibrary;
       this.corouselImage = corouselImage;
       this.tooltip = tooltip;
    }
   
    public Long getFreeAddonId() {
        return this.freeAddonId;
    }
    
    public void setFreeAddonId(Long freeAddonId) {
        this.freeAddonId = freeAddonId;
    }
    public String getLayout() {
        return this.layout;
    }
    
    public void setLayout(String layout) {
        this.layout = layout;
    }
    public String getFont() {
        return this.font;
    }
    
    public void setFont(String font) {
        this.font = font;
    }
    public String getNonWebFont() {
        return this.nonWebFont;
    }
    
    public void setNonWebFont(String nonWebFont) {
        this.nonWebFont = nonWebFont;
    }
    public Boolean getAdvancedSemanticData() {
        return this.advancedSemanticData;
    }
    
    public void setAdvancedSemanticData(Boolean advancedSemanticData) {
        this.advancedSemanticData = advancedSemanticData;
    }
    public Boolean getWcag2() {
        return this.wcag2;
    }
    
    public void setWcag2(Boolean wcag2) {
        this.wcag2 = wcag2;
    }
    public Boolean getDynamicDropDownMenu() {
        return this.dynamicDropDownMenu;
    }
    
    public void setDynamicDropDownMenu(Boolean dynamicDropDownMenu) {
        this.dynamicDropDownMenu = dynamicDropDownMenu;
    }
    public Boolean getDreamweaverCompatability() {
        return this.dreamweaverCompatability;
    }
    
    public void setDreamweaverCompatability(Boolean dreamweaverCompatability) {
        this.dreamweaverCompatability = dreamweaverCompatability;
    }
    public String getBrowserCompatability() {
        return this.browserCompatability;
    }
    
    public void setBrowserCompatability(String browserCompatability) {
        this.browserCompatability = browserCompatability;
    }
    public Boolean getWcag2_1() {
        return this.wcag2_1;
    }
    
    public void setWcag2_1(Boolean wcag2_1) {
        this.wcag2_1 = wcag2_1;
    }
    public String getCssVersion() {
        return this.cssVersion;
    }
    
    public void setCssVersion(String cssVersion) {
        this.cssVersion = cssVersion;
    }
    public Boolean getCommentedCss() {
        return this.commentedCss;
    }
    
    public void setCommentedCss(Boolean commentedCss) {
        this.commentedCss = commentedCss;
    }
    public String getCodingType() {
        return this.codingType;
    }
    
    public void setCodingType(String codingType) {
        this.codingType = codingType;
    }
    public Boolean getCommentedHtml() {
        return this.commentedHtml;
    }
    
    public void setCommentedHtml(Boolean commentedHtml) {
        this.commentedHtml = commentedHtml;
    }
    public Boolean getOptimizedForLoadSpeed() {
        return this.optimizedForLoadSpeed;
    }
    
    public void setOptimizedForLoadSpeed(Boolean optimizedForLoadSpeed) {
        this.optimizedForLoadSpeed = optimizedForLoadSpeed;
    }
    public Boolean getSeoSemanticCoding() {
        return this.seoSemanticCoding;
    }
    
    public void setSeoSemanticCoding(Boolean seoSemanticCoding) {
        this.seoSemanticCoding = seoSemanticCoding;
    }
    public String getJsLibrary() {
        return this.jsLibrary;
    }
    
    public void setJsLibrary(String jsLibrary) {
        this.jsLibrary = jsLibrary;
    }
    public Boolean getCorouselImage() {
        return this.corouselImage;
    }
    
    public void setCorouselImage(Boolean corouselImage) {
        this.corouselImage = corouselImage;
    }
    public Boolean getTooltip() {
        return this.tooltip;
    }
    
    public void setTooltip(Boolean tooltip) {
        this.tooltip = tooltip;
    }




}


