package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * WebDesignOrdernow generated by hbm2java
 */
public class WebDesignOrdernow  implements java.io.Serializable {


     private Long webdesignOrderId;
     private long contactDetailsId;
     private Long htmlFreeAddonId;
     private Long htmlPaidAddonId;
     private Boolean isRevamp;
     private Boolean isQuoted;

    public WebDesignOrdernow() {
    }

	
    public WebDesignOrdernow(long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public WebDesignOrdernow(long contactDetailsId, Long htmlFreeAddonId, Long htmlPaidAddonId, Boolean isRevamp, Boolean isQuoted) {
       this.contactDetailsId = contactDetailsId;
       this.htmlFreeAddonId = htmlFreeAddonId;
       this.htmlPaidAddonId = htmlPaidAddonId;
       this.isRevamp = isRevamp;
       this.isQuoted = isQuoted;
    }
   
    public Long getWebdesignOrderId() {
        return this.webdesignOrderId;
    }
    
    public void setWebdesignOrderId(Long webdesignOrderId) {
        this.webdesignOrderId = webdesignOrderId;
    }
    public long getContactDetailsId() {
        return this.contactDetailsId;
    }
    
    public void setContactDetailsId(long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public Long getHtmlFreeAddonId() {
        return this.htmlFreeAddonId;
    }
    
    public void setHtmlFreeAddonId(Long htmlFreeAddonId) {
        this.htmlFreeAddonId = htmlFreeAddonId;
    }
    public Long getHtmlPaidAddonId() {
        return this.htmlPaidAddonId;
    }
    
    public void setHtmlPaidAddonId(Long htmlPaidAddonId) {
        this.htmlPaidAddonId = htmlPaidAddonId;
    }
    public Boolean getIsRevamp() {
        return this.isRevamp;
    }
    
    public void setIsRevamp(Boolean isRevamp) {
        this.isRevamp = isRevamp;
    }
    public Boolean getIsQuoted() {
        return this.isQuoted;
    }
    
    public void setIsQuoted(Boolean isQuoted) {
        this.isQuoted = isQuoted;
    }




}


