package wh.model;
// Generated May 2, 2015 9:19:20 PM by Hibernate Tools 3.2.1.GA



/**
 * WordpressOrdernow generated by hbm2java
 */
public class WordpressOrdernow  implements java.io.Serializable {


     private Long wordpressOrderId;
     private long contactDetailsId;
     private Long htmlFreeAddonId;
     private Long htmlPaidAddonId;
     private Boolean isTheme;
     private Boolean isPlugin;
     private Boolean isQuoted;
     private Integer numberOfHomePage;
     private Integer numberOfSubpage;

    public WordpressOrdernow() {
    }

	
    public WordpressOrdernow(long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public WordpressOrdernow(long contactDetailsId, Long htmlFreeAddonId, Long htmlPaidAddonId, Boolean isTheme, Boolean isPlugin, Boolean isQuoted, Integer numberOfHomePage, Integer numberOfSubpage) {
       this.contactDetailsId = contactDetailsId;
       this.htmlFreeAddonId = htmlFreeAddonId;
       this.htmlPaidAddonId = htmlPaidAddonId;
       this.isTheme = isTheme;
       this.isPlugin = isPlugin;
       this.isQuoted = isQuoted;
       this.numberOfHomePage = numberOfHomePage;
       this.numberOfSubpage = numberOfSubpage;
    }
   
    public Long getWordpressOrderId() {
        return this.wordpressOrderId;
    }
    
    public void setWordpressOrderId(Long wordpressOrderId) {
        this.wordpressOrderId = wordpressOrderId;
    }
    public long getContactDetailsId() {
        return this.contactDetailsId;
    }
    
    public void setContactDetailsId(long contactDetailsId) {
        this.contactDetailsId = contactDetailsId;
    }
    public Long getHtmlFreeAddonId() {
        return this.htmlFreeAddonId;
    }
    
    public void setHtmlFreeAddonId(Long htmlFreeAddonId) {
        this.htmlFreeAddonId = htmlFreeAddonId;
    }
    public Long getHtmlPaidAddonId() {
        return this.htmlPaidAddonId;
    }
    
    public void setHtmlPaidAddonId(Long htmlPaidAddonId) {
        this.htmlPaidAddonId = htmlPaidAddonId;
    }
    public Boolean getIsTheme() {
        return this.isTheme;
    }
    
    public void setIsTheme(Boolean isTheme) {
        this.isTheme = isTheme;
    }
    public Boolean getIsPlugin() {
        return this.isPlugin;
    }
    
    public void setIsPlugin(Boolean isPlugin) {
        this.isPlugin = isPlugin;
    }
    public Boolean getIsQuoted() {
        return this.isQuoted;
    }
    
    public void setIsQuoted(Boolean isQuoted) {
        this.isQuoted = isQuoted;
    }
    public Integer getNumberOfHomePage() {
        return this.numberOfHomePage;
    }
    
    public void setNumberOfHomePage(Integer numberOfHomePage) {
        this.numberOfHomePage = numberOfHomePage;
    }
    public Integer getNumberOfSubpage() {
        return this.numberOfSubpage;
    }
    
    public void setNumberOfSubpage(Integer numberOfSubpage) {
        this.numberOfSubpage = numberOfSubpage;
    }




}


